#!/usr/bin/env bash
# 1-install_nginx_web_server

echo -e "Updating package lists and installing Nginx...\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo -e "Setting up Nginx and firewall...\n"
sudo service nginx start
sudo ufw allow 'Nginx HTTP'

echo -e "Configuring website files...\n"
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

sudo sed -i '/^}/i \\n    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html >/dev/null
sudo sed -i 's/#error_page 404 \/404.html;/error_page 404 \/404.html;/' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a \\n    location = /error_404.html {\n        root /var/www/html;\n    }' /etc/nginx/sites-available/default

sudo service nginx restart

echo -e "Nginx installation and configuration completed successfully!\n"
