#!/usr/bin/env bash
# 1-install_nginx_web_server

echo -e "Updating package lists and installing Nginx...\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html >/dev/null
sudo sed -i 's/#error_page 404 \/404.html;/error_page 404 \/404.html;/' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a \\n    location = /error_404.html {\n        root /var/www/html;\n    }' /etc/nginx/sites-available/default

sudo service nginx restart

echo -e "Nginx installation and configuration completed successfully!\n"
